#ifndef MAIN_COMMANDLIST_H
#define MAIN_COMMANDLIST_H

/**
 * Список всех команд
 */
enum class CommandsList{
    INIT = 0, FULL, BLACKHOLE, ENTER, COPYPASTE, MOVEFILE, DELETE, SQUEZZE, COMMANDSAMOUNT
};

#endif //MAIN_COMMANDLIST_H
